const SEND_TO_SERVER = 'SEND_TO_SERVER'
const SEND_TO_CLIENT = 'SEND_TO_CLIENT'
const UPDATE_USERS_ONLINE = 'UPDATE_USERS_ONLINE'

const SYSTEM_USER_HELLO = 'SYSTEM_USER_HELLO'

export default { SEND_TO_SERVER, SEND_TO_CLIENT, SYSTEM_USER_HELLO, UPDATE_USERS_ONLINE }
