const SEND_TO_SERVER = 'SEND_TO_SERVER'
const SEND_TO_CLIENT = 'SEND_TO_CLIENT'
const SEND_TO_CLIENT_CLEAR_HISTORY = 'SEND_TO_CLIENT_CLEAR_HISTORY'
const SEND_TO_SERVER_CLEAR_HISTORY = 'SEND_TO_SERVER_CLEAR_HISTORY'
const SEND_ERROR_TO_CLIENT = 'SEND_ERROR_TO_CLIENT'
const UPDATE_USERS_ONLINE = 'UPDATE_USERS_ONLINE'
const SYSTEM_USER_HELLO = 'SYSTEM_USER_HELLO'

export default {
  SEND_TO_SERVER,
  SEND_TO_CLIENT,
  SEND_TO_CLIENT_CLEAR_HISTORY,
  SEND_TO_SERVER_CLEAR_HISTORY,
  SYSTEM_USER_HELLO,
  UPDATE_USERS_ONLINE,
  SEND_ERROR_TO_CLIENT
}
