export const GET_PRIVATE_CHATS = 'GET_PRIVATE_CHATS'
export const SELECT_PRIVATE_CHAT = 'SELECT_PRIVATE_CHAT'
export const SEND_MESSAGE_TO_PRIVATE_CHAT = 'SEND_MESSAGE_TO_PRIVATE_CHAT'
export const CREATE_PRIVATE_CHAT = 'CREATE_PRIVATE_CHAT'
